{
 "title": "Materialize Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "User Org Data Correctness ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sql_user_org_mismatch" }
   ]
  },
  { "title": "Resources Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Usage per Computing Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sql_cluster_replica_usage{cluster_type=\"compute\",col=\"cpu_percent\"}",
     "legendFormat": "{{ cluster_name }}"
    }
   ]
  },
  {
   "title": "Memory Usage per Computing Cluster",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sql_cluster_replica_usage{cluster_type=\"compute\",col=\"memory_percent\"}",
     "legendFormat": "{{ cluster_name }}"
    }
   ]
  }
 ]
}